// Registry of Jokers, Relics, Enhancements, Boss Blinds.
// Pure data: keys, names, rarity, triggers, and effect descriptors.
// Behavior is implemented in the respective engines.

const JOKER_RARITY = {
  COMMON: "common",
  UNCOMMON: "uncommon",
  RARE: "rare",
  LEGENDARY: "legendary",
};

const jokers = [
  // COMMON (14)
  {
    key: "clean_cut",
    name: "Clean Cut",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_blind_end",
    description:
      "If you clear the blind using exactly one hand, gain +2× multiplier.",
  },
  {
    key: "high_card",
    name: "High Card",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_hand_scored",
    description: "Hands valued 19 or higher gain +1× multiplier.",
  },
  {
    key: "suit_stitch",
    name: "Suit Stitch",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_hand_scored",
    description:
      "If a scoring hand contains at least two cards of the same suit, gain +1× multiplier.",
  },
  {
    key: "face_value",
    name: "Face Value",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_hand_scored",
    description: "Each face card in a scoring hand adds +10 base points.",
  },
  {
    key: "ace_up",
    name: "Ace Up",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_hand_value",
    description: "Aces are more likely to count as 11, favoring soft hands.",
  },
  {
    key: "double_down",
    name: "Double Down",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_first_hand_of_round",
    description: "The first hand played each round gains +1× multiplier.",
  },
  {
    key: "even_odds",
    name: "Even Odds",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_hand_scored",
    description: "Even-valued hands gain +20 base points.",
  },
  {
    key: "odd_luck",
    name: "Odd Luck",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_hand_scored",
    description: "Odd-valued hands gain +1× multiplier.",
  },
  {
    key: "dealers_smile",
    name: "Dealer's Smile",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_blackjack",
    description: "The first Blackjack each round gains +1× multiplier.",
  },
  {
    key: "thin_margin",
    name: "Thin Margin",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_hand_scored",
    description: "Hands with exactly two cards gain +30 base points.",
  },
  {
    key: "late_stay",
    name: "Late Stay",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_stay",
    description: "Staying at 20 or 21 grants +1× multiplier.",
  },
  {
    key: "soft_touch",
    name: "Soft Touch",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_bust",
    description: "Busts apply reduced Fragile instead of the normal amount.",
  },
  {
    key: "stacked_deck",
    name: "Stacked Deck",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_blind_end",
    description: "If all hands score during the blind, gain +1× multiplier.",
  },
  {
    key: "low_stakes",
    name: "Low Stakes",
    rarity: JOKER_RARITY.COMMON,
    trigger: "on_hand_scored",
    description: "Hands under 18 still score half base points.",
  },

  // UNCOMMON (12)
  {
    key: "fortune_joker",
    name: "Fortune Joker",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_blackjack_scored",
    description: "+2 gold per Blackjack.",
  },
  {
    key: "mirror_hand",
    name: "Mirror Hand",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_hands_scored",
    description: "Highest hand copies multiplier.",
  },
  {
    key: "suit_tyrant",
    name: "Suit Tyrant",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_hand_scored",
    description: "Mono-suit +3×, mixed suits −1×.",
  },
  {
    key: "face_parade",
    name: "Face Parade",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_hand_scored",
    description: "Each face card grants +0.5× multiplier.",
  },
  {
    key: "split_memory_joker",
    name: "Split Memory",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_split",
    description: "First split doesn’t consume a hand.",
  },
  {
    key: "risk_premium",
    name: "Risk Premium",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_bust",
    description: "Bust → +2× next round.",
  },
  {
    key: "double_vision",
    name: "Double Vision",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_first_enhancement",
    description: "First enhancement triggers twice.",
  },
  {
    key: "lucky_draw",
    name: "Lucky Draw",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_first_draw",
    description: "First draw has 20% chance to duplicate.",
  },
  {
    key: "gold_lining",
    name: "Gold Lining",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_blind_end",
    description: "Clear with ≤2 hands → +1 gold.",
  },
  {
    key: "chain_reaction",
    name: "Chain Reaction",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_21_after_first",
    description: "Each 21 after the first → +1×.",
  },
  {
    key: "dealers_tell",
    name: "Dealer's Tell",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_hit_preview",
    description: "Peek next card before Hit.",
  },
  {
    key: "pressure_cooker",
    name: "Pressure Cooker",
    rarity: JOKER_RARITY.UNCOMMON,
    trigger: "on_hand_scored",
    description: "Each Fragile stack grants +0.5× multiplier.",
  },

  // RARE (10)
  {
    key: "split_joker",
    name: "Split Joker",
    rarity: JOKER_RARITY.RARE,
    trigger: "on_run_state",
    description: "Max hands 3 → 5.",
  },
  {
    key: "lucky_sevens",
    name: "Lucky Sevens",
    rarity: JOKER_RARITY.RARE,
    trigger: "on_hand_scored",
    description: "Each 7 grants +2×; 777 grants +5×.",
  },
  {
    key: "crown_of_kings",
    name: "Crown of Kings",
    rarity: JOKER_RARITY.RARE,
    trigger: "on_hand_scored",
    description: "Each King grants +1.5×.",
  },
  {
    key: "devils_bargain",
    name: "Devil's Bargain",
    rarity: JOKER_RARITY.RARE,
    trigger: "on_intentional_bust",
    description: "Intentional bust → +2× permanent, −2 gold.",
  },
  {
    key: "blackjack_engine",
    name: "Blackjack Engine",
    rarity: JOKER_RARITY.RARE,
    trigger: "on_blackjack_scored",
    description: "Each Blackjack grants +1× permanent.",
  },
  {
    key: "suit_alchemy",
    name: "Suit Alchemy",
    rarity: JOKER_RARITY.RARE,
    trigger: "on_hand_scored",
    description: "Each unique suit grants +1×.",
  },
  {
    key: "blood_counter",
    name: "Blood Counter",
    rarity: JOKER_RARITY.RARE,
    trigger: "on_bust",
    description: "Bust adds +50 base points.",
  },
  {
    key: "echo_split",
    name: "Echo Split",
    rarity: JOKER_RARITY.RARE,
    trigger: "on_split",
    description: "Split duplicates highest card.",
  },
  {
    key: "debt_spiral",
    name: "Debt Spiral",
    rarity: JOKER_RARITY.RARE,
    trigger: "on_run_state",
    description: "+5 gold; Fragile stacks twice as fast.",
  },
  {
    key: "perfect_storm",
    name: "Perfect Storm",
    rarity: JOKER_RARITY.RARE,
    trigger: "on_all_hands_21",
    description: "If all hands hit 21, gain +10×.",
  },

  // LEGENDARY (4)
  {
    key: "endless_twenty_one",
    name: "Endless Twenty-One",
    rarity: JOKER_RARITY.LEGENDARY,
    trigger: "on_21_scored",
    description: "Each 21 grants +1× permanent.",
  },
  {
    key: "house_always_loses",
    name: "House Always Loses",
    rarity: JOKER_RARITY.LEGENDARY,
    trigger: "on_bust_scored",
    description: "Bust halves base instead of zero.",
  },
  {
    key: "golden_devil",
    name: "Golden Devil",
    rarity: JOKER_RARITY.LEGENDARY,
    trigger: "on_bust",
    description: "Bust → +3×, +1 gold, Fragile doubles.",
  },
  {
    key: "final_hand_joker",
    name: "Final Hand",
    rarity: JOKER_RARITY.LEGENDARY,
    trigger: "on_blind_scored",
    description: "Only highest hand scores; multiplier ×3 on that hand.",
  },
];

const relics = [
  {
    key: "golden_ledger",
    name: "Golden Ledger",
    trigger: "on_round_end",
    description: "Gain +1 gold after every round.",
  },
  {
    key: "loaded_deck",
    name: "Loaded Deck",
    trigger: "on_card_draw",
    description: "Face cards are 10% more likely to be drawn.",
  },
  {
    key: "black_seal",
    name: "Black Seal",
    trigger: "on_blackjack_scored",
    description: "Each Blackjack removes 1 Fragile stack.",
  },
  {
    key: "dealers_favor",
    name: "Dealer's Favor",
    trigger: "on_first_shop_purchase",
    description: "The first shop item you buy costs 1 less gold.",
  },
  {
    key: "split_memory_relic",
    name: "Split Memory",
    trigger: "on_split",
    description: "The first split each round does not consume a hand slot.",
  },
  {
    key: "grave_marker",
    name: "Grave Marker",
    trigger: "on_bust_scored",
    description: "Busts add base score instead of scoring zero.",
  },
  {
    key: "vault_key",
    name: "Vault Key",
    trigger: "on_shop_reroll",
    description: "Rerolls cost 1 less gold.",
  },
  {
    key: "echo_relic",
    name: "Echo Relic",
    trigger: "on_first_enhancement",
    description: "The first enhancement applied each round triggers twice.",
  },
  {
    key: "blood_contract",
    name: "Blood Contract",
    trigger: "on_bust",
    description: "Each bust permanently grants +1× multiplier.",
  },
  {
    key: "broken_compass",
    name: "Broken Compass",
    trigger: "on_ante_start",
    description: "Boss blind effects are revealed before the Boss Blind.",
  },
];

const enhancements = [
  {
    key: "suit_changer",
    name: "Suit Changer",
    trigger: "on_enhancement_apply",
    description: "Change the suit of three selected cards.",
  },
  {
    key: "card_mimic",
    name: "Card Mimic",
    trigger: "on_enhancement_apply",
    description: "Copy the rank and suit of another card.",
  },
  {
    key: "blackjack_booster",
    name: "Blackjack Booster",
    trigger: "on_blackjack_scored",
    description: "Blackjacks gain +2× multiplier.",
  },
  {
    key: "face_crown",
    name: "Face Crown",
    trigger: "on_hand_scored",
    description: "Face cards gain +1× multiplier.",
  },
  {
    key: "rank_ascension",
    name: "Rank Ascension",
    trigger: "on_enhancement_apply",
    description: "Increase this card’s rank by +1.",
  },
  {
    key: "golden_frame",
    name: "Golden Frame",
    trigger: "on_hand_scored",
    description: "If this card is part of a 21, gain +1 gold.",
  },
  {
    key: "cursed_edge",
    name: "Cursed Edge",
    trigger: "on_hand_scored_and_bust",
    description: "Gain +3× multiplier. If you bust, Fragile gained is doubled.",
  },
  {
    key: "phantom_ink",
    name: "Phantom Ink",
    trigger: "on_hand_scored",
    description: "This card counts as two ranks for scoring only.",
  },
  {
    key: "twin_sigil",
    name: "Twin Sigil",
    trigger: "on_round_start",
    description: "This card duplicates itself once per round.",
  },
  {
    key: "void_border",
    name: "Void Border",
    trigger: "on_bust",
    description: "This card ignores bust rules once per round.",
  },
];

const bosses = [
  {
    key: "boss_cutter",
    name: "The Cutter",
    ante: 1,
    trigger: "on_hand_scored",
    description: "Hands valued 20 or 21 lose 20 base points before multiplier.",
  },
  {
    key: "boss_misdeal",
    name: "The Misdeal",
    ante: 1,
    trigger: "on_round_start",
    description:
      "First card drawn is revealed, rejected, and replaced with the next card.",
  },
  {
    key: "boss_taxman",
    name: "The Taxman",
    ante: 1,
    trigger: "on_shop_enter",
    description: "All shop items cost +1 gold this round.",
  },
  {
    key: "boss_grinder",
    name: "The Grinder",
    ante: 2,
    trigger: "on_bust",
    description: "Busts apply +2 Fragile instead of the normal amount.",
  },
  {
    key: "boss_tightening",
    name: "The Tightening",
    ante: 2,
    trigger: "on_round_start",
    description: "Each hand may Hit only twice this round.",
  },
  {
    key: "boss_short_stack",
    name: "The Short Stack",
    ante: 2,
    trigger: "on_hand_scored",
    description: "Hands valued under 17 score 0, ignoring all modifiers.",
  },
  {
    key: "boss_dealers_due",
    name: "The Dealer's Due",
    ante: 3,
    trigger: "on_round_end",
    description: "Lose 2 gold at the end of the round.",
  },
  {
    key: "boss_inflation",
    name: "The Inflation",
    ante: 3,
    trigger: "on_shop_enter",
    description: "Rerolls cost +2 additional gold this round.",
  },
  {
    key: "boss_leak",
    name: "The Leak",
    ante: 3,
    trigger: "on_hit",
    description: "Each Hit costs 1 gold this round.",
  },
  {
    key: "boss_crackdown",
    name: "The Crackdown",
    ante: 4,
    trigger: "on_round_start",
    description: "Split is disabled for the entire round.",
  },
  {
    key: "boss_jammer",
    name: "The Jammer",
    ante: 4,
    trigger: "on_round_start",
    description: "The leftmost Joker is disabled for this round.",
  },
  {
    key: "boss_scramble",
    name: "The Scramble",
    ante: 4,
    trigger: "on_round_start",
    description:
      "All card suits are treated as random suits for scoring this round.",
  },
  {
    key: "boss_final_hand",
    name: "The Final Hand",
    ante: 5,
    trigger: "on_blind_scored",
    description: "Only the highest-scoring hand counts; all others score 0.",
  },
  {
    key: "boss_overload",
    name: "The Overload",
    ante: 5,
    trigger: "on_hand_scored",
    description: "Every scoring hand applies +1 Fragile.",
  },
  {
    key: "boss_void",
    name: "The Void",
    ante: 5,
    trigger: "on_hand_scored",
    description: "All base points are halved before multiplier.",
  },
];

module.exports = {
  JOKER_RARITY,
  jokers,
  relics,
  enhancements,
  bosses,
};
